### ISSUE TITLE
Global symbol "$results" requires explicit package name at ../Pearl-SMPP-Server/Pearl/SMPP/Server.pm line 714.

### ISSUE THREAD

**Issue by sah-anshu** [radetsky/Pearl-SMPP-Server#1]
Hi

I am getting error at line 714 for $result variable. Can this be ignored. 
# Logs:

Global symbol "$results" requires explicit package name at ../Pearl-SMPP-Server/Pearl/SMPP/Server.pm line 714.
BEGIN not safe after errors--compilation aborted at ../Pearl-SMPP-Server/Pearl/SMPP/Server.pm line 735.
Compilation failed in require at smppd3.pl line 28.
BEGIN failed--compilation aborted at smppd3.pl line 28.
# CODE

  foreach my $id ( keys %{ $PDUs } ) { 
    warn "PDU -> $system_id:\n" . Dumper SMPP::Packet::unpack_pdu($PDUs->{$id}); 
    my $result = syswrite $socket, $PDUs->{$id};
    unless ( defined ( $result ) ) { 
      warn "Can't write to socket: " . Dumper $socket . "\nBecause: $!"; 
      close $socket; 
      $this->close_connection($host,$port); 
    }
    warn "Written to socket $results bytes." if $this->{'debug'};
  }

Regards
Anshu

**Comment by radetsky** [comment]
It's fixed around year ago. You can update code from repository.
